# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: Observe_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - float_joint
    - base_to_wheel_left_joint
    - base_to_wheel_right_joint
    - wam/base_yaw_joint
    - wam/shoulder_pitch_joint
    - wam/shoulder_yaw_joint
    - wam/elbow_pitch_joint
    - wam/wrist_yaw_joint
    - wam/wrist_pitch_joint
    - wam/palm_yaw_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS



controller_manager_ns: controller_manager
controller_list:
  - name: arm/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - wam/base_yaw_joint
      - wam/shoulder_pitch_joint
      - wam/shoulder_yaw_joint
      - wam/elbow_pitch_joint
      - wam/wrist_yaw_joint
      - wam/wrist_pitch_joint
      - wam/palm_yaw_joint

arm: 
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - wam/base_yaw_joint
      - wam/shoulder_pitch_joint
      - wam/shoulder_yaw_joint
      - wam/elbow_pitch_joint
      - wam/wrist_yaw_joint
      - wam/wrist_pitch_joint
      - wam/palm_yaw_joint
    gains:
      wam/base_yaw_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      wam/shoulder_pitch_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      wam/shoulder_yaw_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      wam/elbow_pitch_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      wam/wrist_yaw_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      wam/wrist_pitch_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      wam/palm_yaw_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1

initial:  # Define initial robot poses.
  - group: arm
    pose: Observe_pose